config:
  env: development
  port: 8080
  hostname: http://shortify
pgsql:
  host: postgres://postgres:x@localhost:5432/shortify
  entryPoint: ./init.sql
redis:
  url: redis://localhost:6379
  database: 0