version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
#      - POSTGRES_HOST=pgsql
#      - POSTGRES_PORT=5432
#      - POSTGRES_USER=exampleuser
#      - POSTGRES_PASSWORD=examplepass
#      - POSTGRES_DB=exampledb
#      - MONGO_HOST=mongo
#      - MONGO_PORT=27017
#      - MONGO_DB=exampledb
#    depends_on:
#      - pgsql
#      - mongo

#  pgsql:
#    image: postgres:13
#    ports:
#      - "5430:5432"
#    environment:
#      POSTGRES_USER: exampleuser
#      POSTGRES_PASSWORD: examplepass
#      POSTGRES_DB: exampledb
#    volumes:
#      - pgsql-data:/var/lib/postgresql/data
#
#  mongo:
#    image: mongo:5
#    ports:
#      - "27010:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    volumes:
#      - mongo-data:/data/db
#
#volumes:
#  pgsql-data:
#  mongo-data: