global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shortify'
    static_configs:
      - targets: ['shortify:8080'] 
  - job_name: 'shortify-read'
    static_configs:
      - targets: ['shortify-read:8081'] 